# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://Liu-Feng-deeplearning.github.io

date_format: "ordinal"
title: "Liufeng's Blogs"
subtitle: "liufeng's Coding Life"
description: "Share My Coding Life"

keywords: LiuFeng
timezone: Asia/Shenzhen
encoding: "utf-8"
side_bar_repo_limit: 5

# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-05-03
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: 闷骚的程序员

# ---------------- #
#      Author      #
# ---------------- #
author: LiuFeng
organization: 
organization_url: 
github_username: Liu-Feng-deeplearning
location: ShenZhen, China
email: liufeng900204@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Category

   -
     href: /archives/
     label: 归档

  -
    href: /wiki/
    label: Wiki

#  -
#    href: /links/
#    label: Link

  -
    href: /about/
    label: AboutMe

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Liu-Feng-deeplearning/Liu-Feng-deeplearning.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Liu-Feng-deeplearning
    repo: Liu-Feng-deeplearning.github.io
    clientID: Iv1.8ce95076d61852f2
    clientSecret: 78d18b39ed5b9a5e668718a6d2753b0537457cb2

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-134594282-1
